# Generated by Django 4.2 on 2023-04-08 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsapp', '0002_clinicsuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinicsuser',
        ),
    ]
